openapi: 3.0.0
info:
  version: 1.0.0
  title: Simple Artist API
  description: A simple API to illustrate OpenAPI concepts

servers:
  - url: https://example.io/v1

# Basic authentication
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []

paths:
  /artists:
    get:
     description: Returns a list of artists
     responses:
       '200':
         description: Succesfully returned a list of artists
         content:
           application/json:
             schema:
               type: array
               items:
                 type: object
                 required:
                   - username
                 properties:
                   artist_name:
                     type: string
                   artist_genre:
                     type: string
                   albums_recorded:
                     type: integer
                   username:
                     type: string
       '400':
         description: Invalid request
         content:
           application/json:
             schema:
               type: object
               properties:
                 message:
                   type: string